name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Pylin GitHub Action
      uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pytest test/unit
